# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)


Category.create(name: 'Electronics', premium: false)
Category.create(name: 'Furniture', premium: false)
Category.create(name: 'Antiques', premium: false)
Category.create(name: 'Appliances', premium: false)
Category.create(name: 'Arts & Crafts', premium: false)
Category.create(name: 'Auto Parts', premium: false)
Category.create(name: 'Aviation', premium: false)
Category.create(name: 'Baby & Kids', premium: false)
Category.create(name: 'Barter', premium: false)
Category.create(name: 'Beauty & Health', premium: false)
Category.create(name: 'Bike Parts', premium: false)
Category.create(name: 'Books', premium: false)
Category.create(name: 'Cars & Trucks', premium: false)
Category.create(name: 'CD/DVD/VHS', premium: false)
Category.create(name: 'Cell Phones', premium: false)
Category.create(name: 'Clothes & Acc', premium: false)
Category.create(name: 'Collectibles', premium: false)
Category.create(name: 'Computer Parts', premium: false)
Category.create(name: 'Computers', premium: false)
Category.create(name: 'Farm & Garden', premium: false)
Category.create(name: 'Household', premium: false)
Category.create(name: 'Jewelry', premium: false)
Category.create(name: 'Materials', premium: false)
Category.create(name: 'Motorcycle Parts', premium: false)
Category.create(name: 'Motorcycles', premium: false)
Category.create(name: 'Music Instruments', premium: false)
Category.create(name: 'Photo & Video', premium: false)
Category.create(name: 'Sporting', premium: false)
Category.create(name: 'Tools', premium: false)
Category.create(name: 'Toys & Games', premium: false)
Category.create(name: 'Video Games', premium: false)
Category.create(name: 'Wanted', premium: false)
Category.create(name: 'Wheels & Tires', premium: false)

Location.create(name: 'Manhattan')
Location.create(name: 'Brooklyn')
Location.create(name: 'Queens')
Location.create(name: 'The Bronx')
Location.create(name: 'Staten Island')
